"""initial migration with all models

Revision ID: a7e09b7774b2
Revises:
Create Date: 2025-12-08 14:20:32.254680

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a7e09b7774b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
