"""
Brief document generator for the Client Research feature.

Produces a formatted client brief in three formats:
  - Markdown (.md) — plain text, no dependencies
  - DOCX (.docx)   — python-docx (already a project dependency)
  - PDF (.pdf)     — reportlab (pure Python)

All generators accept a ClientBrief plus an optional confidence dict
(field_name → 0.0–1.0) and return raw bytes ready to stream.
"""

# mypy: disable-error-code="import-untyped"

from datetime import datetime
from io import BytesIO
from typing import Dict, List, Optional

from ..models.client_brief import ClientBrief

_SECTION_SEP = "\n" + "─" * 60 + "\n"


# ── Markdown ──────────────────────────────────────────────────────────────


def _conf_tag(confidence: Dict[str, float], key: str) -> str:
    """Return a short confidence marker for Markdown output."""
    score = confidence.get(key, 0.0)
    if score >= 0.7:
        return " ✅"
    if score >= 0.4:
        return " ⚡"
    return ""


def generate_markdown(brief: ClientBrief, confidence: Optional[Dict[str, float]] = None) -> bytes:
    conf = confidence or {}
    now = datetime.now().strftime("%B %d, %Y")
    lines: List[str] = [
        f"# Client Brief — {brief.company_name}",
        f"*Generated by Client Research Agent · {now}*",
        "",
        "---",
        "",
        "## Business Overview",
        f"**Company:** {brief.company_name}",
    ]
    if brief.founder_name:
        lines.append(f"**Founder:** {brief.founder_name}{_conf_tag(conf, 'founder_name')}")
    if brief.location:
        lines.append(f"**Location:** {brief.location}")
    if brief.industry:
        lines.append(f"**Industry:** {brief.industry}{_conf_tag(conf, 'industry')}")
    lines += [
        "",
        f"**Business Description:**{_conf_tag(conf, 'business_description')}",
        f"{brief.business_description}",
        "",
        "---",
        "",
        "## Target Audience",
        f"**Ideal Customer:**{_conf_tag(conf, 'ideal_customer')}",
        f"{brief.ideal_customer}",
        "",
        f"**Main Problem Solved:**{_conf_tag(conf, 'main_problem_solved')}",
        f"{brief.main_problem_solved}",
    ]
    if brief.customer_pain_points:
        lines += ["", f"**Pain Points:**{_conf_tag(conf, 'customer_pain_points')}"]
        for pt in brief.customer_pain_points:
            lines.append(f"- {pt}")
    if brief.customer_questions:
        lines += ["", "**Common Customer Questions:**"]
        for q in brief.customer_questions:
            lines.append(f"- {q}")
    lines += ["", "---", "", "## Brand Voice & Tone"]
    if brief.tone_preference:
        lines.append(f"**Tone:** {brief.tone_preference.value}{_conf_tag(conf, 'tone_preference')}")
    if brief.brand_personality:
        lines.append(
            f"**Brand Personality:**{_conf_tag(conf, 'brand_personality')} "
            + ", ".join(brief.brand_personality)
        )
    if brief.tone_to_avoid:
        lines.append(f"**Avoid:** {brief.tone_to_avoid}")
    if brief.key_phrases:
        lines += ["", f"**Key Phrases:**{_conf_tag(conf, 'key_phrases')}"]
        for kp in brief.key_phrases:
            lines.append(f"- {kp}")
    if brief.main_cta:
        lines.append(f"\n**Primary CTA:**{_conf_tag(conf, 'main_cta')} {brief.main_cta}")
    lines += ["", "---", "", "## Market Intelligence"]
    if brief.competitors:
        lines += [f"**Competitors:**{_conf_tag(conf, 'competitors')}"]
        for c in brief.competitors:
            lines.append(f"- {c}")
    if brief.keywords:
        lines += ["", f"**Keywords:**{_conf_tag(conf, 'keywords')} " + ", ".join(brief.keywords)]
    if brief.measurable_results:
        lines += [
            "",
            f"**Measurable Results:**{_conf_tag(conf, 'measurable_results')}",
            brief.measurable_results,
        ]
    if brief.target_platforms:
        lines += [
            "",
            f"**Platforms:**{_conf_tag(conf, 'target_platforms')} "
            + ", ".join(p.value for p in brief.target_platforms),
        ]
    if brief.posting_frequency:
        lines.append(f"**Posting Frequency:** {brief.posting_frequency}")
    lines += [
        "",
        "---",
        "",
        "*✅ = high confidence · ⚡ = medium confidence · (no marker) = low confidence*",
    ]
    return "\n".join(lines).encode("utf-8")


# ── DOCX ──────────────────────────────────────────────────────────────────


def generate_docx(brief: ClientBrief, confidence: Optional[Dict[str, float]] = None) -> bytes:
    from docx import Document  # type: ignore[import]
    from docx.shared import Pt, RGBColor  # type: ignore[import]
    from docx.enum.text import WD_ALIGN_PARAGRAPH  # type: ignore[import]

    conf = confidence or {}
    doc = Document()

    # ── Title block ──
    title = doc.add_heading(f"Client Brief — {brief.company_name}", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub = doc.add_paragraph(
        f"Generated {datetime.now().strftime('%B %d, %Y')} · Client Research Agent"
    )
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.color.rgb = RGBColor(127, 140, 141)
    doc.add_paragraph()

    def section(title_text: str):
        doc.add_heading(title_text, level=1)

    def field(label: str, value: str, conf_key: str = ""):
        score = conf.get(conf_key, 0.0) if conf_key else 0.0
        badge = " ✅" if score >= 0.7 else " ⚡" if score >= 0.4 else ""
        p = doc.add_paragraph()
        run_label = p.add_run(f"{label}: ")
        run_label.bold = True
        p.add_run(f"{value}{badge}")

    def bullet_list(label: str, items: List[str], conf_key: str = ""):
        score = conf.get(conf_key, 0.0) if conf_key else 0.0
        badge = " ✅" if score >= 0.7 else " ⚡" if score >= 0.4 else ""
        p = doc.add_paragraph()
        run_label = p.add_run(f"{label}{badge}:")
        run_label.bold = True
        for item in items:
            doc.add_paragraph(item, style="List Bullet")

    # ── Business Overview ──
    section("Business Overview")
    field("Company", brief.company_name)
    if brief.founder_name:
        field("Founder", brief.founder_name, "founder_name")
    if brief.location:
        field("Location", brief.location)
    if brief.industry:
        field("Industry", brief.industry, "industry")
    p = doc.add_paragraph()
    p.add_run("Business Description: ").bold = True
    score = conf.get("business_description", 0.0)
    badge = " ✅" if score >= 0.7 else " ⚡" if score >= 0.4 else ""
    p.add_run(f"{brief.business_description}{badge}")

    # ── Target Audience ──
    section("Target Audience")
    p = doc.add_paragraph()
    p.add_run("Ideal Customer: ").bold = True
    score = conf.get("ideal_customer", 0.0)
    p.add_run(f"{brief.ideal_customer}{' ✅' if score >= 0.7 else ' ⚡' if score >= 0.4 else ''}")
    p = doc.add_paragraph()
    p.add_run("Main Problem Solved: ").bold = True
    score = conf.get("main_problem_solved", 0.0)
    p.add_run(
        f"{brief.main_problem_solved}{' ✅' if score >= 0.7 else ' ⚡' if score >= 0.4 else ''}"
    )
    if brief.customer_pain_points:
        bullet_list("Pain Points", brief.customer_pain_points, "customer_pain_points")
    if brief.customer_questions:
        bullet_list("Customer Questions", brief.customer_questions)

    # ── Brand Voice ──
    section("Brand Voice & Tone")
    if brief.tone_preference:
        field("Tone", brief.tone_preference.value, "tone_preference")
    if brief.brand_personality:
        field("Brand Personality", ", ".join(brief.brand_personality), "brand_personality")
    if brief.tone_to_avoid:
        field("Avoid", brief.tone_to_avoid)
    if brief.key_phrases:
        bullet_list("Key Phrases", brief.key_phrases, "key_phrases")
    if brief.main_cta:
        field("Primary CTA", brief.main_cta, "main_cta")

    # ── Market Intelligence ──
    section("Market Intelligence")
    if brief.competitors:
        bullet_list("Competitors", brief.competitors, "competitors")
    if brief.keywords:
        field("Keywords", ", ".join(brief.keywords), "keywords")
    if brief.measurable_results:
        field("Measurable Results", brief.measurable_results, "measurable_results")
    if brief.target_platforms:
        field("Platforms", ", ".join(p.value for p in brief.target_platforms), "target_platforms")
    if brief.posting_frequency:
        field("Posting Frequency", brief.posting_frequency)

    doc.add_paragraph()
    footer = doc.add_paragraph(
        "✅ high confidence · ⚡ medium confidence · (no marker) low confidence"
    )
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(127, 140, 141)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── PDF ───────────────────────────────────────────────────────────────────


def generate_pdf(brief: ClientBrief, confidence: Optional[Dict[str, float]] = None) -> bytes:
    from reportlab.lib import colors  # type: ignore[import]
    from reportlab.lib.pagesizes import LETTER  # type: ignore[import]
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle  # type: ignore[import]
    from reportlab.lib.units import inch  # type: ignore[import]
    from reportlab.platypus import (  # type: ignore[import]
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        HRFlowable,
        ListFlowable,
        ListItem,
    )

    conf = confidence or {}
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()
    brand_color = colors.HexColor("#2980b9")

    title_style = ParagraphStyle(
        "BriefTitle",
        parent=styles["Title"],
        textColor=brand_color,
        fontSize=20,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "BriefSubtitle",
        parent=styles["Normal"],
        textColor=colors.HexColor("#7f8c8d"),
        fontSize=10,
        spaceAfter=12,
    )
    h1_style = ParagraphStyle(
        "BriefH1",
        parent=styles["Heading1"],
        textColor=brand_color,
        fontSize=13,
        spaceBefore=14,
        spaceAfter=6,
        borderPad=(0, 0, 2, 0),
    )
    label_style = ParagraphStyle(
        "BriefLabel",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
    )
    footer_style = ParagraphStyle(
        "BriefFooter",
        parent=styles["Normal"],
        textColor=colors.HexColor("#7f8c8d"),
        fontSize=8,
        spaceAfter=0,
    )

    def conf_badge(key: str) -> str:
        score = conf.get(key, 0.0)
        if score >= 0.7:
            return ' <font color="#27ae60">✓ high</font>'
        if score >= 0.4:
            return ' <font color="#e67e22">~ medium</font>'
        return ""

    def field_para(label: str, value: str, conf_key: str = "") -> Paragraph:
        badge = conf_badge(conf_key) if conf_key else ""
        return Paragraph(f"<b>{label}:</b> {value}{badge}", label_style)

    story = []

    # Title
    story.append(Paragraph(f"Client Brief — {brief.company_name}", title_style))
    story.append(
        Paragraph(
            f"Generated {datetime.now().strftime('%B %d, %Y')} · Client Research Agent",
            subtitle_style,
        )
    )
    story.append(HRFlowable(width="100%", color=brand_color, thickness=1))
    story.append(Spacer(1, 12))

    # Business Overview
    story.append(Paragraph("Business Overview", h1_style))
    story.append(field_para("Company", brief.company_name))
    if brief.founder_name:
        story.append(field_para("Founder", brief.founder_name, "founder_name"))
    if brief.location:
        story.append(field_para("Location", brief.location))
    if brief.industry:
        story.append(field_para("Industry", brief.industry, "industry"))
    badge = conf_badge("business_description")
    story.append(Paragraph(f"<b>Business Description{badge}:</b>", label_style))
    story.append(Paragraph(brief.business_description, label_style))

    # Target Audience
    story.append(Paragraph("Target Audience", h1_style))
    story.append(field_para("Ideal Customer", brief.ideal_customer, "ideal_customer"))
    story.append(
        field_para("Main Problem Solved", brief.main_problem_solved, "main_problem_solved")
    )
    if brief.customer_pain_points:
        badge = conf_badge("customer_pain_points")
        story.append(Paragraph(f"<b>Pain Points{badge}:</b>", label_style))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(pt, label_style)) for pt in brief.customer_pain_points],
                bulletType="bullet",
                leftIndent=16,
            )
        )
    if brief.customer_questions:
        story.append(Paragraph("<b>Customer Questions:</b>", label_style))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(q, label_style)) for q in brief.customer_questions],
                bulletType="bullet",
                leftIndent=16,
            )
        )

    # Brand Voice
    story.append(Paragraph("Brand Voice & Tone", h1_style))
    if brief.tone_preference:
        story.append(field_para("Tone", brief.tone_preference.value, "tone_preference"))
    if brief.brand_personality:
        story.append(
            field_para("Personality", ", ".join(brief.brand_personality), "brand_personality")
        )
    if brief.tone_to_avoid:
        story.append(field_para("Avoid", brief.tone_to_avoid))
    if brief.key_phrases:
        badge = conf_badge("key_phrases")
        story.append(Paragraph(f"<b>Key Phrases{badge}:</b>", label_style))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(kp, label_style)) for kp in brief.key_phrases],
                bulletType="bullet",
                leftIndent=16,
            )
        )
    if brief.main_cta:
        story.append(field_para("Primary CTA", brief.main_cta, "main_cta"))

    # Market Intelligence
    story.append(Paragraph("Market Intelligence", h1_style))
    if brief.competitors:
        badge = conf_badge("competitors")
        story.append(Paragraph(f"<b>Competitors{badge}:</b>", label_style))
        story.append(
            ListFlowable(
                [ListItem(Paragraph(c, label_style)) for c in brief.competitors],
                bulletType="bullet",
                leftIndent=16,
            )
        )
    if brief.keywords:
        story.append(field_para("Keywords", ", ".join(brief.keywords), "keywords"))
    if brief.measurable_results:
        story.append(
            field_para("Measurable Results", brief.measurable_results, "measurable_results")
        )
    if brief.target_platforms:
        story.append(
            field_para(
                "Platforms",
                ", ".join(p.value for p in brief.target_platforms),
                "target_platforms",
            )
        )
    if brief.posting_frequency:
        story.append(field_para("Posting Frequency", brief.posting_frequency))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#ecf0f1"), thickness=1))
    story.append(
        Paragraph(
            "✓ high confidence · ~ medium confidence · (no marker) low confidence",
            footer_style,
        )
    )

    doc.build(story)
    return buf.getvalue()
